name: App1 Bug
description: Report issues extension
title: "[App1 Bug]: "
labels: ["bug", "app1"]
body:
  - type: markdown
    attributes:
      value: '# App1 Bug'
  - type: markdown
    attributes:
      value: |
        specific instructions or information for the issue.
        Read more at [Google](google.com)
  - type: input
    id: app1_input1
    attributes:
      label: app1_input1
      description: "important input 1"
      placeholder: "input1 place holder"
    validations:
      required: true
  - type: input
    id: app1_input2
    attributes:
      label: app1_input2
      description: "important input 2"
      placeholder: "input2 place holder"
    validations:
      required: true
  - type: input
    id: app1_input3
    attributes:
      label: app1_input3
      description: "important input 3"
      placeholder: "input3 place holder"
    validations:
      required: true
  - type: input
    id: app1_input4
    attributes:
      label: app1_input4
      description: "important input 4"
      placeholder: "input4 place holder"
    validations:
      required: true
  - type: input
    id: app1_input5
    attributes:
      label: app1_input5
      description: "important input 5"
      placeholder: "input5 place holder"
    validations:
      required: true
